# Generated by Django 5.2.17 on 2026-09-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('car', 'Car'), ('scooter', 'Scooter')], max_length=20)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_tzs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('seats', models.CharField(max_length=30)),
                ('transmission', models.CharField(default='Automatic', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
