# Generated by Django 5.2.17 on 2026-09-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalmedia',
            name='is_hero',
            field=models.BooleanField(default=False),
        ),
    ]
